version: '3'

services:
  mongo:
    container_name: mongodb
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "store"
      MONGO_INITDB_ROOT_PASSWORD: "store123"
    ports:
      - "27017:27017"
    networks:
      - local
    
  app:
    depends_on:
      - mongo
    container_name: store_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./:/home/app
    networks: 
      - local

networks:
  local:
    name: local